"""create initial postgresql schema

Revision ID: 20260825_0001
Revises:
Create Date: 2026-08-25 00:17:17.078551
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260825_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'user'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    op.create_index('uq_app_user_username_lower', 'app_user', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('auth_session',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name='fk_auth_session_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_auth_session'))
    )
    op.create_index('ix_auth_session_user_expires', 'auth_session', ['user_id', 'expires_at'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('structured_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name='fk_resume_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume')),
    sa.UniqueConstraint('id', 'user_id', name='uq_resume_id_user_id')
    )
    op.create_index('ix_resume_user_created_id', 'resume', ['user_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('interview_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rtc_room_id', sa.String(length=255), nullable=False),
    sa.Column('rtc_user_id', sa.String(length=255), nullable=False),
    sa.Column('rtc_task_id', sa.String(length=255), nullable=False),
    sa.Column('rtc_callback_id', sa.String(length=255), nullable=False),
    sa.Column('rtc_status', sa.String(length=32), server_default=sa.text("'created'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id', 'user_id'], ['resume.id', 'resume.user_id'], name='fk_interview_session_resume_owner', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name='fk_interview_session_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_session')),
    sa.UniqueConstraint('id', 'user_id', name='uq_interview_session_id_user_id'),
    sa.UniqueConstraint('rtc_callback_id', name='uq_interview_session_rtc_callback_id'),
    sa.UniqueConstraint('rtc_room_id', name='uq_interview_session_rtc_room_id'),
    sa.UniqueConstraint('rtc_task_id', name='uq_interview_session_rtc_task_id'),
    sa.UniqueConstraint('rtc_user_id', name='uq_interview_session_rtc_user_id')
    )
    op.create_index('ix_interview_session_user_started_id', 'interview_session', ['user_id', sa.literal_column('started_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_interview_session_user_status_started_id', 'interview_session', ['user_id', 'status', sa.literal_column('started_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('interview_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'session'"), nullable=False),
    sa.Column('md_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id', 'user_id'], ['interview_session.id', 'interview_session.user_id'], name='fk_interview_report_session_owner', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name='fk_interview_report_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_report')),
    sa.UniqueConstraint('id', 'user_id', name='uq_interview_report_id_user_id')
    )
    op.create_index('ix_interview_report_user_created_id', 'interview_report', ['user_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], name='fk_message_session', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message')),
    sa.UniqueConstraint('session_id', 'seq', name='uq_message_session_seq')
    )
    op.create_index('ix_message_session_created_id', 'message', ['session_id', 'created_at', 'id'], unique=False)
    op.create_table('recording',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('ext', sa.String(length=32), nullable=True),
    sa.Column('tos_key', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('asr_task_id', sa.String(length=255), nullable=True),
    sa.Column('transcript_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id', 'user_id'], ['interview_report.id', 'interview_report.user_id'], name='fk_recording_report_owner', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name='fk_recording_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recording'))
    )
    op.create_index('ix_recording_user_created_id', 'recording', ['user_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.execute('GRANT USAGE ON SCHEMA public TO deepscout_app, deepscout_analytics')
    op.execute('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO deepscout_app')
    op.execute('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO deepscout_app')
    op.execute('GRANT SELECT ON ALL TABLES IN SCHEMA public TO deepscout_analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('REVOKE SELECT ON ALL TABLES IN SCHEMA public FROM deepscout_analytics')
    op.execute('REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM deepscout_app')
    op.execute('REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM deepscout_app')
    op.execute('REVOKE USAGE ON SCHEMA public FROM deepscout_app, deepscout_analytics')
    op.drop_index('ix_recording_user_created_id', table_name='recording')
    op.drop_table('recording')
    op.drop_index('ix_message_session_created_id', table_name='message')
    op.drop_table('message')
    op.drop_index('ix_interview_report_user_created_id', table_name='interview_report')
    op.drop_table('interview_report')
    op.drop_index('ix_interview_session_user_status_started_id', table_name='interview_session')
    op.drop_index('ix_interview_session_user_started_id', table_name='interview_session')
    op.drop_table('interview_session')
    op.drop_index('ix_resume_user_created_id', table_name='resume')
    op.drop_table('resume')
    op.drop_index('ix_auth_session_user_expires', table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_index('uq_app_user_username_lower', table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
