"""enforce one report per interview session

Revision ID: 20260825_0002
Revises: 20260825_0001
Create Date: 2026-08-25 10:27:27.262022
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260825_0002'
down_revision: Union[str, Sequence[str], None] = '20260825_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_interview_report_session_id', 'interview_report', ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_interview_report_session_id', 'interview_report', type_='unique')
    # ### end Alembic commands ###
